services:  
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: ["9972:1972","52773:52773","9090:8080"]
    container_name: tryaidevelop
    volumes: ["./data:/data","./src:/src"]
    environment: 
      - TZ=JST-9
